name: Publish Python Wheel

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags: "*"

jobs:
  publish-wheels:
    name: Publish Wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Build Weel
        run: |
          pip install wheel twine
          python setup.py sdist bdist_wheel
      - name: Deploy to PyPI on Tags
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload --skip-existing dist/*
      - name: Make index
        uses: banesullivan/create-pip-index-action@main
        with:
          package_directory: dist
      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
